trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'windows-2019'

steps:

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: '**/*.nuspec'
    versioningScheme: byPrereleaseNumber

- task: NuGetCommand@2
  displayName: 'NugGet push'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'nuget'